#####################################################################################################
#$$$$$$\  $$\   $$\ $$$$$$$$\  $$$$$$\  $$\       $$$$$$\   $$$$$$\   $$$$$$\  $$$$$$$$\ $$$$$$$\   #
#$$  __$$\ $$ |  $$ |\__$$  __|$$  __$$\ $$ |     $$  __$$\ $$  __$$\ $$  __$$\ $$  _____|$$  __$$\ #
#$$ /  $$ |$$ |  $$ |   $$ |   $$ /  $$ |$$ |     $$ /  $$ |$$ /  \__|$$ /  \__|$$ |      $$ |  $$ |#
#$$$$$$$$ |$$ |  $$ |   $$ |   $$ |  $$ |$$ |     $$ |  $$ |$$ |$$$$\ $$ |$$$$\ $$$$$\    $$$$$$$  |#
#$$  __$$ |$$ |  $$ |   $$ |   $$ |  $$ |$$ |     $$ |  $$ |$$ |\_$$ |$$ |\_$$ |$$  __|   $$  __$$< #
#$$ |  $$ |$$ |  $$ |   $$ |   $$ |  $$ |$$ |     $$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |      $$ |  $$ |#
#$$ |  $$ |\$$$$$$  |   $$ |    $$$$$$  |$$$$$$$$\ $$$$$$  |\$$$$$$  |\$$$$$$  |$$$$$$$$\ $$ |  $$ |#
#\__|  \__| \______/    \__|    \______/ \________|\______/  \______/  \______/ \________|\__|  \__|#
#####################################################################################################
#This plugin is made by SkyfightTV for everyone
#It works only in Spigot/Bukkit 1.16.4
#This plugin can be reloaded

FolderPath: "logs"

ColorConsole: true

AutoCleanup:
  Enable: true
  #Maximum lifetime of the file in days, after this time the file will be deleted
  MaxFileLife: 7

##############################################
# __  __  ___  ____  _   _ _     _____ ____  #
#|  \/  |/ _ \|  _ \| | | | |   | ____/ ___| #
#| |\/| | | | | | | | | | | |   |  _| \___ \ #
#| |  | | |_| | |_| | |_| | |___| |___ ___) |#
#|_|  |_|\___/|____/ \___/|_____|_____|____/ #
##############################################
#Enable or disable modules
#This modules are all events supported by AutoLogger
#/!\ Warning : Beware of certain events that can be called many times
#and that can generate a heavy log file or even lag on the server.
#Like : PlayerMove or PlayerInteract /!\

#After update, reload the plugin or restart the server

Modules:
  BlockBreak: true
  BlockPlace: true
  EntityDamage: true
  EntityExplode: true
  EntityShootBow: true
  EntitySpawn: true
  EntityTarget: true
  PlayerBedEnter: true
  PlayerBedLeave: true
  PlayerBucketEmpty: true
  PlayerBucketFill: true
  PlayerChangedWorld: true
  PlayerChat: true
  PlayerChatTabComplete: true
  PlayerCommandPreprocess: true
  PlayerDeath: true
  PlayerDropItem: true
  PlayerExpChange: true
  PlayerFish: true
  PlayerGameModeChange: true
  PlayerInteractAtEntity: true
  PlayerInteract: true
  PlayerItemBreak: true
  PlayerItemConsume: true
  PlayerItemDamage: true
  PlayerItemHeld: true
  PlayerJoin: true
  PlayerKick: true
  PlayerLevelChange: true
  PlayerMove: true
  PlayerPickupArrow: true
  PlayerPickupItem: true
  PlayerPortal: true
  PlayerQuit: true
  PlayerRespawn: true
  PlayerTeleport: true

###########################################################################
#  ____ ___  _   _ _____ ___ ____ _   _ ____      _  _____ ___ ___  _   _ #
#/ ___/ _ \| \ | |  ___|_ _/ ___| | | |  _ \    / \|_   _|_ _/ _ \| \ | | #
#| |  | | | |  \| | |_   | | |  _| | | | |_) |  / _ \ | |  | | | | |  \| |#
#| |__| |_| | |\  |  _|  | | |_| | |_| |  _ <  / ___ \| |  | | |_| | |\  |#
#\____\___/|_| \_|_|   |___\____|\___/|_| \_\/_/   \_\_| |___\___/|_| \_| #
###########################################################################

#Informations:
#FolderName = name of the folder where all files of this event are created
#FileName = name of the file created inside folder
#Message = text written in the file each time the event is called

#GlobalVariables:
#%date% = hh:mm:ss
#%playername% = name of the player
#%worldname% = name of the world where the event took place

#Variables:
#%blockname% = name of the broken block
#%x% = x-coordinate of the broken block
#%y% = y-coordinate of the broken block
#%z% = z-coordinate of the broken block
#%itemname% = name of the item use to broke the block
BlockBreak:
  FolderName: "AutoLogger_BlockBreak"
  FileName: "%date%-%filenumber%"
  Message:  "[%date%] %playername% : %blockname% in %worldname% at %x% %y% %z% with %itemname%"

#Variables:
#%blockname% = name of the placed block
#%x% = x-coordinate of the placed block
#%y% = y-coordinate of the placed block
#%z% = z-coordinate of the placed block
BlockPlace:
  FolderName: "AutoLogger_BlockPlace"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %blockname% in %worldname% at %x% %y% %z%"

#Variables:
#%entity% = name of the entity
#%cause% = cause of the damage
#%damage% = number of damage get by the entity
#%x% = x-coordinate of the entity
#%y% = y-coordinate of the entity
#%z% = z-coordinate of the entity
EntityDamage:
  FolderName: "AutoLogger_EntityDamage"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : (%cause%) %entity% get %damage% damage in %worldname% at %x% %y% %z%"

#Variables:
#%entity% = name of the entity
#%x% = x-coordinate of the entity
#%y% = y-coordinate of the entity
#%z% = z-coordinate of the entity
EntityExplode:
  FolderName: "AutoLogger_EntityExplode"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %entity% in %worldname% at %x% %y% %z%"

#Variables:
#%entity% = name of the entity
#%x% = x-coordinate of the entity
#%y% = y-coordinate of the entity
#%z% = z-coordinate of the entity
EntityExplode:
  FolderName: "AutoLogger_EntityExplode"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %entity% in %worldname% at %x% %y% %z%"


#Variables:
#%bedenterresult% = result of the event
#%x% = x-coordinate of the bed
#%y% = y-coordinate of the bed
#%z% = z-coordinate of the bed
PlayerBedEnter:
  FolderName: "AutoLogger_PlayerBedEnter"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : (%bedenterresult%) in %worldname% at %x% %y% %z%"

#Variables:
#%x% = x-coordinate of the bed
#%y% = y-coordinate of the bed
#%z% = z-coordinate of the bed
PlayerBedLeave:
  FolderName: "AutoLogger_PlayerBedLeave"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %worldname% at %x% %y% %z%"

#Variables:
#%bucket% = name of the bucket
#%x% = x-coordinate of the clicked block
#%y% = y-coordinate of the clicked block
#%z% = z-coordinate of the clicked block
PlayerBucketEmpty:
  FolderName: "AutoLogger_PlayerBucketEmpty"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %bucket% in %worldname% at %x% %y% %z%"

#Variables:
#%bucket% = name of the bucket
#%x% = x-coordinate of the clicked block
#%y% = y-coordinate of the clicked block
#%z% = z-coordinate of the clicked block
PlayerBucketFill:
  FolderName: "AutoLogger_PlayerBucketFill"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %bucket% in %worldname% at %x% %y% %z%"

#Variable:
#%from% = name of the world from the player
PlayerChangedWorld:
  FolderName: "AutoLogger_PlayerChangedWorld"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %from% -> %worldname%"

#Variable:
#%message% = message send by the player
PlayerChat:
  FolderName: "AutoLogger_PlayerChat"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %message%"

#Variable:
#%message% = message being tab-completed
PlayerChatTabComplete:
  FolderName: "AutoLogger_PlayerChatTabComplete"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %message%"

#Variable:
#%command% = command send by the player
PlayerCommandPreprocess:
  FolderName: "AutoLogger_PlayerCommandPreprocess"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %command%"

#Variables:
#%stuff% = dead player stuff
#%x% = dead player's x coordinates
#%y% = dead player's y coordinates
#%z% = dead player's z coordinates
#%message% = death message
PlayerDeath:
  FolderName: "AutoLogger_PlayerDeath"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %stuff%"

#Variables:
#%amount% = number of items dropped
#%item% = name of the dropped items
#%x% = x-coordinate of the dropped items
#%y% = y-coordinate of the dropped items
#%z% = z-coordinate of the dropped items
PlayerDropItem:
  FolderName: "AutoLogger_PlayerDropItem"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %amount%x %item% in %worldname% at %x% %y% %z%"

#Variables:
#%amount% = number of experiences the gambler has had
#%x% = x-coordinate gain of experience
#%y% = y-coordinate gain of experience
#%z% = z-coordinate gain of experience
PlayerExpChange:
  FolderName: "AutoLogger_PlayerExpChange"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : get %amount% exp in %worldname% at %x% %y% %z%"

#Variables:
#%fish% = name of the fish caught
#%exp% = number of experiences the gambler has had
#%x% = x-coordinate of the sinful player
#%y% = y-coordinate of the sinful player
#%z% = z-coordinate of the sinful player
PlayerFish:
  FolderName: "AutoLogger_PlayerFish"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %fish% and %exp% exp in %worldname% at %x% %y% %z%"

#Variables:
#%previous% = previous gamemode
#%new% = next gamemode
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerGameModeChange:
  FolderName: "AutoLogger_PlayerGameModeChange"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %previous% -> %new% in %worldname% at %x% %y% %z%"

#Variables:
#%action% = action made by the player
#%block% = block clicked by the player
#%item% = utility item by clicking
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerInteract:
  FolderName: "AutoLogger_PlayerInteract"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : (%action%) %block% in %worldname% at %x% %y% %z% with %item%"

#Variables:
#%entity% = block clicked by the player
#%item% = utility item by clicking
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerInteractAtEntity:
  FolderName: "AutoLogger_PlayerInteractAtEntity"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %entity% in %worldname% at %x% %y% %z% with %item%"

#Variables:
#%item% = item that broke
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerItemBreak:
  FolderName: "AutoLogger_PlayerItemBreak"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %item% in %worldname% at %x% %y% %z%"

#Variables:
#%item% = item that consume
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerItemConsume:
  FolderName: "AutoLogger_PlayerItemConsume"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %item% in %worldname% at %x% %y% %z%"

#Variables:
#%item% = item that consume
#%damage% = damage that took the item
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerItemDamage:
  FolderName: "AutoLogger_PlayerItemDamage"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %item% took %damage% in %worldname% at %x% %y% %z%"

#Variables:
#%previous% = previous item
#%new% = new item
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerItemHeld:
  FolderName: "AutoLogger_PlayerItemHeld"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %previous% to %new% in %worldname% at %x% %y% %z%"

#Variables:
#%message% = message when leaving
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerJoin:
  FolderName: "AutoLogger_PlayerJoin"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : join in %worldname% at %x% %y% %z%"

#Variables:
#%message% = message when kicking
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerKick:
  FolderName: "AutoLogger_PlayerKick"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %message% in %worldname% at %x% %y% %z%"

#Variables:
#%old% = old exp level
#%new% = new exp level
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerLevelChange:
  FolderName: "AutoLogger_PlayerLevelChange"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : join in %worldname% at %x% %y% %z%"

#Variables:
#%fromx% = x-coordinate where the player comes from
#%fromy% = y-coordinate where the player comes from
#%fromz% = z-coordinate where the player comes from
#%tox% = coordinate x where the player goes
#%toy% = coordinate y where the player goes
#%toz% = coordinate z where the player goes
PlayerMove:
  FolderName: "AutoLogger_PlayerMove"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %fromx% %fromy% %fromz% --> %tox% %toy% %toz% in %worldname%"


#Variables:
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerPickupArrow:
  FolderName: "AutoLogger_PlayerPickupArrow"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %x% %y% %z% in %worldname%"


#Variables:
#%item% = name of the item picked up
#%amount% = Number of items picked up
#%x% = x-coordinate of the player
#%y% = y-coordinate of the player
#%z% = z-coordinate of the player
PlayerPickupItem:
  FolderName: "AutoLogger_PlayerPickupItem"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %amount%x %item% in %worldname% at %x% %y% %z%"


#Variables:
#%fromx% = x-coordinate where the player comes from
#%fromy% = y-coordinate where the player comes from
#%fromz% = z-coordinate where the player comes from
#%tox% = coordinate x where the player goes
#%toy% = coordinate y where the player goes
#%toz% = coordinate z where the player goes
PlayerPortal:
  FolderName: "AutoLogger_PlayerPortal"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %fromx% %fromy% %fromz% --> %tox% %toy% %toz% in %worldname%"


#Variables:
#%message% = message when leaving
PlayerQuit:
  FolderName: "AutoLogger_PlayerQuit"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %message% in %worldname% at %x% %y% %z%"


#Variables:
#%x% = coordinate x where the player respawn
#%y% = coordinate y where the player respawn
#%z% = coordinate z where the player respawn
PlayerRespawn:
  FolderName: "AutoLogger_PlayerRespawn"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : %x% %y% %z% in %worldname%"


#Variables:
#%cause% = cause of teleportation
#%fromworldname% = world where the player comes from
#%fromx% = x-coordinate where the player comes from
#%fromy% = y-coordinate where the player comes from
#%fromz% = z-coordinate where the player comes from
#%tox% = coordinate x where the player goes
#%toy% = coordinate y where the player goes
#%toz% = coordinate z where the player goes
PlayerTeleport:
  FolderName: "AutoLogger_onPlayerTeleport"
  FileName: "%date%-%filenumber%"
  Message: "[%date%] %playername% : (%cause%) %fromworldname% at %fromx% %fromy% %fromz% -> %worldname% at %tox% %toy% %toz%"