name: AutoLogger
main: fr.skyfighttv.autologger.Main
version: 1.0
api-version: 1.16
commands:
  logs:
    usage: "/logs"
    permission: "logs"
    description: "Send all activated logs to the Player"